# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - TaskNetWeb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x ".git/*" "node_modules/*" "*.git*" "tests/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy using Kudu ZipDeploy API
        env:
          AZURE_PUBLISH_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_87AC31E09D394EBA9C14222FF4930CBA }}
        run: |
          # Install XML parser
          sudo apt-get update && sudo apt-get install -y libxml2-utils

          # Extract values from publish profile
          PUBLISH_URL=$(echo "$AZURE_PUBLISH_PROFILE" | xmllint --xpath "string(//publishProfile[contains(@publishUrl, '.scm.azurewebsites.net')]/publishUrl)" - | sed 's/:443$//')
          USERNAME=$(echo "$AZURE_PUBLISH_PROFILE" | xmllint --xpath "string(//publishProfile[contains(@publishUrl, '.scm.azurewebsites.net')]/userName)" -)
          PASSWORD=$(echo "$AZURE_PUBLISH_PROFILE" | xmllint --xpath "string(//publishProfile[contains(@publishUrl, '.scm.azurewebsites.net')]/userPWD)" -)

            echo "Deploying to: $PUBLISH_URL"

          # Push ZIP to Kudu zipdeploy API
          curl -X POST -u "$USERNAME:$PASSWORD" \
            -T release.zip \
            "https://$PUBLISH_URL/api/zipdeploy"