name: Next.js CI

on:
  push:
    branches: ['*', '*/*', '**']
  pull_request:
    branches: ['*', '*/*', '**']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' #Any node version
          cache: 'npm' 

      - name: Install dependencies
        run: npm ci

      - name: Run JEST tests
        run: npm test

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ runner.os }}
  
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' #Any node version
          cache: 'npm' 

      - name: Install dependencies
        run: npm ci

      - name: Run lint check
        run: npm run lint

      - name: Build application
        run: npm run build
        env:
          CI: true

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ runner.os }}
